use crate::config::HostOverride;
use anyhow::Result;
use std::collections::HashMap;
use tracing::info;

#[derive(Debug, Clone)]
pub struct DnsConfig {
    pub primary: String,
    pub fallback: String,
    pub ru: String,
    pub hosts: Vec<HostOverride>,
}

impl DnsConfig {
    pub fn map(&self) -> HashMap<String, Vec<String>> {
        let mut m = HashMap::new();
        for h in &self.hosts {
            m.insert(h.domain.clone(), h.ips.clone());
        }
        m
    }

    pub fn hosts_file_content(&self) -> String {
        let mut s = String::from("# generated by unblocker — do not edit manually\n");
        for h in &self.hosts {
            for ip in &h.ips {
                s.push_str(&format!("{} {}\n", ip, h.domain));
            }
        }
        s
    }

    pub fn singbox_dns_rules(&self) -> serde_json::Value {
        let rules: Vec<serde_json::Value> = self
            .hosts
            .iter()
            .map(|h| {
                serde_json::json!({
                    "domain": [h.domain.clone()],
                    "server": h.ips.join(",")
                })
            })
            .collect();
        serde_json::json!({
            "servers": [
                {"tag":"doh-primary","address": self.primary, "strategy":"ipv4_only"},
                {"tag":"doh-ru","address": self.ru, "strategy":"ipv4_only"},
                {"tag":"doh-fallback","address": self.fallback, "strategy":"ipv4_only"},
                {"tag":"local","address":"local"}
            ],
            "rules": rules,
            "final": "doh-primary"
        })
    }
}

pub async fn probe_doh(url: &str, domain: &str) -> Result<Vec<String>> {
    let client = reqwest::Client::builder()
        .timeout(std::time::Duration::from_secs(4))
        .build()?;
    let resp = client
        .get(url)
        .header("accept", "application/dns-json")
        .query(&[("name", domain), ("type", "A")])
        .send()
        .await?;
    let v: serde_json::Value = resp.json().await?;
    let mut out = Vec::new();
    if let Some(arr) = v.get("Answer").and_then(|a| a.as_array()) {
        for a in arr {
            if let Some(data) = a.get("data").and_then(|d| d.as_str()) {
                if data.parse::<std::net::IpAddr>().is_ok() {
                    out.push(data.to_string());
                }
            }
        }
    }
    Ok(out)
}

pub async fn refresh_hosts_via_doh(cfg: &DnsConfig, domains: &[String]) -> Vec<HostOverride> {
    let mut out = Vec::new();
    for d in domains {
        for url in [&cfg.primary, &cfg.ru, &cfg.fallback] {
            match probe_doh(url, d).await {
                Ok(ips) if !ips.is_empty() => {
                    info!(domain=%d, ips=?ips, via=%url, "DoH resolved");
                    out.push(HostOverride {
                        domain: d.clone(),
                        ips,
                    });
                    break;
                }
                _ => continue,
            }
        }
    }
    out
}
